// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "FileHandler": {
      /**
       * LoadList
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "LoadList": () => {
        return window.go.main.FileHandler.LoadList();
      },
      /**
       * SaveList
       * @param {RawMessage} arg1 - Go Type: json.RawMessage
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "SaveList": (arg1) => {
        return window.go.main.FileHandler.SaveList(arg1);
      },
    },
  },

};
export default go;
